/* Données : verbes + phrases.
 * groupe1 (-er) et groupe2 (-ir/-issons) : conjugaison générée automatiquement (voir app.js),
 *   avec possibilité d'override par forme via "over" (index 0..5).
 * autres : conjugaison complète fournie dans "full" (6 formes, sans pronom).
 * Chaque verbe : inf, en (anglais), ex (phrase FR), exEn (phrase EN).
 */

const DATA = {
  groupe1: {
    label: "1er groupe (verbes en -er)",
    verbs: [
      { inf: "parler",      en: "to speak",         ex: "Je parle français.",            exEn: "I speak French." },
      { inf: "aimer",       en: "to like / to love", ex: "Tu aimes le café.",            exEn: "You like coffee." },
      { inf: "chercher",    en: "to look for",      ex: "Il cherche ses clés.",          exEn: "He is looking for his keys." },
      { inf: "donner",      en: "to give",          ex: "Nous donnons un cadeau.",       exEn: "We give a gift." },
      { inf: "penser",      en: "to think",         ex: "Vous pensez à moi.",            exEn: "You think of me." },
      { inf: "trouver",     en: "to find",          ex: "Ils trouvent la solution.",     exEn: "They find the solution." },
      { inf: "demander",    en: "to ask",           ex: "Je demande l'heure.",           exEn: "I ask the time." },
      { inf: "rester",      en: "to stay",          ex: "Tu restes à la maison.",        exEn: "You stay at home." },
      { inf: "passer",      en: "to pass / spend",  ex: "Il passe le week-end ici.",     exEn: "He spends the weekend here." },
      { inf: "regarder",    en: "to watch / look",  ex: "Nous regardons la télé.",       exEn: "We watch TV." },
      { inf: "aider",       en: "to help",          ex: "Vous aidez vos amis.",          exEn: "You help your friends." },
      { inf: "jouer",       en: "to play",          ex: "Les enfants jouent dehors.",    exEn: "The children play outside." },
      { inf: "écouter",     en: "to listen",        ex: "J'écoute la musique.",          exEn: "I listen to music." },
      { inf: "travailler",  en: "to work",          ex: "Tu travailles beaucoup.",       exEn: "You work a lot." },
      { inf: "montrer",     en: "to show",          ex: "Il montre le chemin.",          exEn: "He shows the way." },
      { inf: "porter",      en: "to carry / wear",  ex: "Je porte un manteau.",          exEn: "I wear a coat." },
      { inf: "manger",      en: "to eat",           ex: "Nous mangeons du pain.",        exEn: "We eat bread.", over: { 3: "mangeons" } },
      { inf: "habiter",     en: "to live (reside)", ex: "Vous habitez à Paris.",         exEn: "You live in Paris." },
      { inf: "arriver",     en: "to arrive",        ex: "Le train arrive à midi.",       exEn: "The train arrives at noon." },
      { inf: "entrer",      en: "to enter",         ex: "J'entre dans la maison.",       exEn: "I enter the house." },
      { inf: "rentrer",     en: "to go/come home",  ex: "Tu rentres ce soir.",           exEn: "You come home tonight." },
      { inf: "laisser",     en: "to leave / let",   ex: "Il laisse la porte ouverte.",   exEn: "He leaves the door open." },
      { inf: "garder",      en: "to keep",          ex: "Nous gardons le secret.",       exEn: "We keep the secret." },
      { inf: "oublier",     en: "to forget",        ex: "Vous oubliez souvent.",         exEn: "You often forget." },
      { inf: "gagner",      en: "to win / earn",    ex: "Ils gagnent le match.",         exEn: "They win the match." },
      { inf: "marcher",     en: "to walk",          ex: "Je marche dans le parc.",       exEn: "I walk in the park." },
      { inf: "commencer",   en: "to start",         ex: "Nous commençons le travail.",   exEn: "We start work.", over: { 3: "commençons" } },
      { inf: "continuer",   en: "to continue",      ex: "Tu continues à lire.",          exEn: "You keep reading." },
      { inf: "acheter",     en: "to buy",           ex: "Il achète du lait.",            exEn: "He buys milk.", over: { 0: "achète", 1: "achètes", 2: "achète", 5: "achètent" } },
      { inf: "coûter",      en: "to cost",          ex: "Ça coûte cher.",                exEn: "That costs a lot." },
      { inf: "tomber",      en: "to fall",          ex: "Je tombe souvent.",             exEn: "I often fall." },
      { inf: "monter",      en: "to go up",         ex: "Tu montes l'escalier.",         exEn: "You go up the stairs." },
      { inf: "danser",      en: "to dance",         ex: "Nous dansons ensemble.",        exEn: "We dance together." },
      { inf: "chanter",     en: "to sing",          ex: "Vous chantez bien.",            exEn: "You sing well." },
      { inf: "dessiner",    en: "to draw",          ex: "Les enfants dessinent.",        exEn: "The children draw." },
      { inf: "voyager",     en: "to travel",        ex: "Nous voyageons en été.",        exEn: "We travel in summer.", over: { 3: "voyageons" } },
      { inf: "cuisiner",    en: "to cook",          ex: "Je cuisine ce soir.",           exEn: "I cook tonight." },
      { inf: "laver",       en: "to wash",          ex: "Tu laves la voiture.",          exEn: "You wash the car." },
      { inf: "fermer",      en: "to close",         ex: "Il ferme la fenêtre.",          exEn: "He closes the window." },
      { inf: "appeler",     en: "to call",          ex: "J'appelle mon ami.",            exEn: "I call my friend.", over: { 0: "appelle", 1: "appelles", 2: "appelle", 5: "appellent" } },
      { inf: "utiliser",    en: "to use",           ex: "Nous utilisons un ordinateur.", exEn: "We use a computer." },
      { inf: "étudier",     en: "to study",         ex: "Vous étudiez le français.",     exEn: "You study French." },
      { inf: "préparer",    en: "to prepare",       ex: "Je prépare le dîner.",          exEn: "I prepare dinner." },
      { inf: "rencontrer",  en: "to meet",          ex: "Tu rencontres des gens.",       exEn: "You meet people." },
      { inf: "expliquer",   en: "to explain",       ex: "Il explique la leçon.",         exEn: "He explains the lesson." },
      { inf: "raconter",    en: "to tell (a story)",ex: "Nous racontons une histoire.",  exEn: "We tell a story." },
      { inf: "téléphoner",  en: "to phone",         ex: "Vous téléphonez à Marie.",      exEn: "You phone Marie." },
      { inf: "voler",       en: "to fly / steal",   ex: "Les oiseaux volent haut.",      exEn: "The birds fly high." },
      { inf: "pleurer",     en: "to cry",           ex: "Le bébé pleure.",               exEn: "The baby cries." },
      { inf: "adorer",      en: "to adore / love",  ex: "J'adore le chocolat.",          exEn: "I love chocolate." }
    ]
  },

  groupe2: {
    label: "2e groupe (verbes en -ir, -issons)",
    verbs: [
      { inf: "finir",      en: "to finish",         ex: "Je finis mes devoirs.",           exEn: "I finish my homework." },
      { inf: "choisir",    en: "to choose",         ex: "Tu choisis un livre.",            exEn: "You choose a book." },
      { inf: "réussir",    en: "to succeed",        ex: "Il réussit l'examen.",            exEn: "He passes the exam." },
      { inf: "grandir",    en: "to grow up",        ex: "Les enfants grandissent vite.",   exEn: "Children grow up fast." },
      { inf: "grossir",    en: "to gain weight",    ex: "Je grossis en hiver.",            exEn: "I gain weight in winter." },
      { inf: "maigrir",    en: "to lose weight",    ex: "Tu maigris un peu.",              exEn: "You lose a little weight." },
      { inf: "rougir",     en: "to blush",          ex: "Elle rougit facilement.",         exEn: "She blushes easily." },
      { inf: "réfléchir",  en: "to think / reflect",ex: "Nous réfléchissons au problème.", exEn: "We think about the problem." },
      { inf: "remplir",    en: "to fill",           ex: "Vous remplissez le verre.",       exEn: "You fill the glass." },
      { inf: "obéir",      en: "to obey",           ex: "Les chiens obéissent.",           exEn: "The dogs obey." },
      { inf: "punir",      en: "to punish",         ex: "Le maître punit l'élève.",        exEn: "The teacher punishes the student." },
      { inf: "guérir",     en: "to heal",           ex: "Le patient guérit vite.",         exEn: "The patient heals quickly." },
      { inf: "ralentir",   en: "to slow down",      ex: "La voiture ralentit.",            exEn: "The car slows down." },
      { inf: "applaudir",  en: "to applaud",        ex: "Nous applaudissons les acteurs.", exEn: "We applaud the actors." },
      { inf: "bâtir",      en: "to build",          ex: "Ils bâtissent une maison.",       exEn: "They build a house." },
      { inf: "saisir",     en: "to grab / seize",   ex: "Je saisis l'occasion.",           exEn: "I seize the opportunity." },
      { inf: "atterrir",   en: "to land",           ex: "L'avion atterrit.",               exEn: "The plane lands." },
      { inf: "définir",    en: "to define",         ex: "Vous définissez le mot.",         exEn: "You define the word." },
      { inf: "établir",    en: "to establish",      ex: "Nous établissons un plan.",       exEn: "We establish a plan." },
      { inf: "franchir",   en: "to cross",          ex: "Il franchit la ligne.",           exEn: "He crosses the line." },
      { inf: "fournir",    en: "to provide",        ex: "Nous fournissons l'aide.",        exEn: "We provide help." },
      { inf: "nourrir",    en: "to feed",           ex: "Je nourris le chat.",             exEn: "I feed the cat." },
      { inf: "avertir",    en: "to warn",           ex: "Tu avertis tes amis.",            exEn: "You warn your friends." },
      { inf: "accomplir",  en: "to accomplish",     ex: "Il accomplit sa mission.",        exEn: "He accomplishes his mission." },
      { inf: "agir",       en: "to act",            ex: "Nous agissons vite.",             exEn: "We act quickly." },
      { inf: "réagir",     en: "to react",          ex: "Vous réagissez bien.",            exEn: "You react well." },
      { inf: "unir",       en: "to unite",          ex: "L'amour unit les gens.",          exEn: "Love unites people." },
      { inf: "réunir",     en: "to gather",         ex: "Nous réunissons la famille.",     exEn: "We gather the family." },
      { inf: "vieillir",   en: "to grow old",       ex: "On vieillit tous.",               exEn: "We all grow old." },
      { inf: "blanchir",   en: "to whiten",         ex: "Le mur blanchit au soleil.",      exEn: "The wall whitens in the sun." },
      { inf: "jaunir",     en: "to turn yellow",    ex: "Les feuilles jaunissent.",        exEn: "The leaves turn yellow." },
      { inf: "salir",      en: "to make dirty",     ex: "Les enfants salissent tout.",     exEn: "The children make everything dirty." },
      { inf: "embellir",   en: "to embellish",      ex: "Le jardin embellit.",             exEn: "The garden grows more beautiful." },
      { inf: "enrichir",   en: "to enrich",         ex: "La lecture enrichit l'esprit.",   exEn: "Reading enriches the mind." },
      { inf: "envahir",    en: "to invade",         ex: "Les fourmis envahissent la cuisine.", exEn: "The ants invade the kitchen." },
      { inf: "fleurir",    en: "to bloom",          ex: "Les fleurs fleurissent au printemps.", exEn: "Flowers bloom in spring." },
      { inf: "refroidir",  en: "to cool down",      ex: "La soupe refroidit.",             exEn: "The soup cools down." },
      { inf: "subir",      en: "to undergo",        ex: "Il subit une opération.",         exEn: "He undergoes surgery." },
      { inf: "trahir",     en: "to betray",         ex: "Tu ne trahis pas tes amis.",      exEn: "You don't betray your friends." },
      { inf: "aboutir",    en: "to lead to",        ex: "Le chemin aboutit à la mer.",     exEn: "The path leads to the sea." },
      { inf: "adoucir",    en: "to soften",         ex: "Le miel adoucit la gorge.",       exEn: "Honey soothes the throat." },
      { inf: "affaiblir",  en: "to weaken",         ex: "La maladie affaiblit le corps.",  exEn: "Illness weakens the body." },
      { inf: "garantir",   en: "to guarantee",      ex: "Nous garantissons la qualité.",   exEn: "We guarantee the quality." },
      { inf: "durcir",     en: "to harden",         ex: "Le ciment durcit.",               exEn: "The cement hardens." },
      { inf: "pâlir",      en: "to turn pale",      ex: "Elle pâlit de peur.",             exEn: "She turns pale with fear." },
      { inf: "surgir",     en: "to emerge",         ex: "Un problème surgit.",             exEn: "A problem arises." },
      { inf: "gémir",      en: "to moan",           ex: "Le malade gémit.",                exEn: "The sick man moans." },
      { inf: "bondir",     en: "to leap",           ex: "Le chat bondit sur la souris.",   exEn: "The cat leaps on the mouse." },
      { inf: "rajeunir",   en: "to rejuvenate",     ex: "Cette coupe te rajeunit.",        exEn: "This haircut makes you look younger." },
      { inf: "verdir",     en: "to turn green",     ex: "La campagne verdit au printemps.",exEn: "The countryside turns green in spring." }
    ]
  },

  autres: {
    label: "Autres verbes (3e groupe, être, avoir…)",
    verbs: [
      { inf: "être",       en: "to be",             ex: "Je suis fatigué.",           exEn: "I am tired.",             full: ["suis","es","est","sommes","êtes","sont"] },
      { inf: "avoir",      en: "to have",           ex: "J'ai faim.",                 exEn: "I am hungry.",           full: ["ai","as","a","avons","avez","ont"] },
      { inf: "aller",      en: "to go",             ex: "Je vais au marché.",         exEn: "I go to the market.",    full: ["vais","vas","va","allons","allez","vont"] },
      { inf: "faire",      en: "to do / make",      ex: "Je fais du sport.",          exEn: "I do sports.",           full: ["fais","fais","fait","faisons","faites","font"] },
      { inf: "dire",       en: "to say",            ex: "Je dis la vérité.",          exEn: "I tell the truth.",      full: ["dis","dis","dit","disons","dites","disent"] },
      { inf: "pouvoir",    en: "can / to be able",  ex: "Je peux venir.",             exEn: "I can come.",            full: ["peux","peux","peut","pouvons","pouvez","peuvent"] },
      { inf: "vouloir",    en: "to want",           ex: "Je veux dormir.",            exEn: "I want to sleep.",       full: ["veux","veux","veut","voulons","voulez","veulent"] },
      { inf: "savoir",     en: "to know (a fact)",  ex: "Je sais nager.",             exEn: "I know how to swim.",    full: ["sais","sais","sait","savons","savez","savent"] },
      { inf: "voir",       en: "to see",            ex: "Je vois la mer.",            exEn: "I see the sea.",         full: ["vois","vois","voit","voyons","voyez","voient"] },
      { inf: "venir",      en: "to come",           ex: "Je viens ce soir.",          exEn: "I come tonight.",        full: ["viens","viens","vient","venons","venez","viennent"] },
      { inf: "devoir",     en: "must / to have to", ex: "Je dois partir.",            exEn: "I must leave.",          full: ["dois","dois","doit","devons","devez","doivent"] },
      { inf: "prendre",    en: "to take",           ex: "Je prends le bus.",          exEn: "I take the bus.",        full: ["prends","prends","prend","prenons","prenez","prennent"] },
      { inf: "mettre",     en: "to put",            ex: "Je mets la table.",          exEn: "I set the table.",       full: ["mets","mets","met","mettons","mettez","mettent"] },
      { inf: "tenir",      en: "to hold",           ex: "Je tiens ta main.",          exEn: "I hold your hand.",      full: ["tiens","tiens","tient","tenons","tenez","tiennent"] },
      { inf: "partir",     en: "to leave",          ex: "Je pars demain.",            exEn: "I leave tomorrow.",      full: ["pars","pars","part","partons","partez","partent"] },
      { inf: "sortir",     en: "to go out",         ex: "Je sors ce soir.",           exEn: "I go out tonight.",      full: ["sors","sors","sort","sortons","sortez","sortent"] },
      { inf: "dormir",     en: "to sleep",          ex: "Je dors bien.",              exEn: "I sleep well.",          full: ["dors","dors","dort","dormons","dormez","dorment"] },
      { inf: "sentir",     en: "to feel / smell",   ex: "Je sens une odeur.",         exEn: "I smell a scent.",       full: ["sens","sens","sent","sentons","sentez","sentent"] },
      { inf: "servir",     en: "to serve",          ex: "Je sers le café.",           exEn: "I serve the coffee.",    full: ["sers","sers","sert","servons","servez","servent"] },
      { inf: "courir",     en: "to run",            ex: "Je cours vite.",             exEn: "I run fast.",            full: ["cours","cours","court","courons","courez","courent"] },
      { inf: "ouvrir",     en: "to open",           ex: "J'ouvre la porte.",          exEn: "I open the door.",       full: ["ouvre","ouvres","ouvre","ouvrons","ouvrez","ouvrent"] },
      { inf: "offrir",     en: "to offer / give",   ex: "J'offre un cadeau.",         exEn: "I give a gift.",         full: ["offre","offres","offre","offrons","offrez","offrent"] },
      { inf: "recevoir",   en: "to receive",        ex: "Je reçois une lettre.",      exEn: "I receive a letter.",    full: ["reçois","reçois","reçoit","recevons","recevez","reçoivent"] },
      { inf: "écrire",     en: "to write",          ex: "J'écris une lettre.",        exEn: "I write a letter.",      full: ["écris","écris","écrit","écrivons","écrivez","écrivent"] },
      { inf: "lire",       en: "to read",           ex: "Je lis un livre.",           exEn: "I read a book.",         full: ["lis","lis","lit","lisons","lisez","lisent"] },
      { inf: "boire",      en: "to drink",          ex: "Je bois de l'eau.",          exEn: "I drink water.",         full: ["bois","bois","boit","buvons","buvez","boivent"] },
      { inf: "croire",     en: "to believe",        ex: "Je crois en toi.",           exEn: "I believe in you.",      full: ["crois","crois","croit","croyons","croyez","croient"] },
      { inf: "vivre",      en: "to live",           ex: "Je vis à Paris.",            exEn: "I live in Paris.",       full: ["vis","vis","vit","vivons","vivez","vivent"] },
      { inf: "suivre",     en: "to follow",         ex: "Je suis le guide.",          exEn: "I follow the guide.",    full: ["suis","suis","suit","suivons","suivez","suivent"] },
      { inf: "connaître",  en: "to know (someone)", ex: "Je connais Marie.",          exEn: "I know Marie.",          full: ["connais","connais","connaît","connaissons","connaissez","connaissent"] },
      { inf: "comprendre", en: "to understand",     ex: "Je comprends la leçon.",     exEn: "I understand the lesson.",full: ["comprends","comprends","comprend","comprenons","comprenez","comprennent"] },
      { inf: "apprendre",  en: "to learn",          ex: "J'apprends le français.",    exEn: "I learn French.",        full: ["apprends","apprends","apprend","apprenons","apprenez","apprennent"] },
      { inf: "attendre",   en: "to wait",           ex: "J'attends le bus.",          exEn: "I wait for the bus.",    full: ["attends","attends","attend","attendons","attendez","attendent"] },
      { inf: "entendre",   en: "to hear",           ex: "J'entends du bruit.",        exEn: "I hear a noise.",        full: ["entends","entends","entend","entendons","entendez","entendent"] },
      { inf: "répondre",   en: "to answer",         ex: "Je réponds à la question.",  exEn: "I answer the question.", full: ["réponds","réponds","répond","répondons","répondez","répondent"] },
      { inf: "perdre",     en: "to lose",           ex: "Je perds mes clés.",         exEn: "I lose my keys.",        full: ["perds","perds","perd","perdons","perdez","perdent"] },
      { inf: "rendre",     en: "to give back",      ex: "Je rends le livre.",         exEn: "I give the book back.",  full: ["rends","rends","rend","rendons","rendez","rendent"] },
      { inf: "vendre",     en: "to sell",           ex: "Je vends ma voiture.",       exEn: "I sell my car.",         full: ["vends","vends","vend","vendons","vendez","vendent"] },
      { inf: "descendre",  en: "to go down",        ex: "Je descends l'escalier.",    exEn: "I go down the stairs.",  full: ["descends","descends","descend","descendons","descendez","descendent"] },
      { inf: "mourir",     en: "to die",            ex: "Je meurs de faim.",          exEn: "I'm starving.",          full: ["meurs","meurs","meurt","mourons","mourez","meurent"] },
      { inf: "rire",       en: "to laugh",          ex: "Je ris beaucoup.",           exEn: "I laugh a lot.",         full: ["ris","ris","rit","rions","riez","rient"] },
      { inf: "conduire",   en: "to drive",          ex: "Je conduis la voiture.",     exEn: "I drive the car.",       full: ["conduis","conduis","conduit","conduisons","conduisez","conduisent"] },
      { inf: "plaire",     en: "to please",         ex: "Tu plais à tout le monde.",  exEn: "Everybody likes you.",   full: ["plais","plais","plaît","plaisons","plaisez","plaisent"] },
      { inf: "devenir",    en: "to become",         ex: "Je deviens fort.",           exEn: "I become strong.",       full: ["deviens","deviens","devient","devenons","devenez","deviennent"] },
      { inf: "revenir",    en: "to come back",      ex: "Je reviens vite.",           exEn: "I come back soon.",      full: ["reviens","reviens","revient","revenons","revenez","reviennent"] },
      { inf: "obtenir",    en: "to obtain / get",   ex: "J'obtiens un bon résultat.", exEn: "I get a good result.",   full: ["obtiens","obtiens","obtient","obtenons","obtenez","obtiennent"] },
      { inf: "mentir",     en: "to lie",            ex: "Je ne mens jamais.",         exEn: "I never lie.",           full: ["mens","mens","ment","mentons","mentez","mentent"] },
      { inf: "naître",     en: "to be born",        ex: "Un bébé naît chaque jour.",  exEn: "A baby is born every day.",full: ["nais","nais","naît","naissons","naissez","naissent"] },
      { inf: "paraître",   en: "to appear / seem",  ex: "Tu parais fatigué.",         exEn: "You seem tired.",        full: ["parais","parais","paraît","paraissons","paraissez","paraissent"] },
      { inf: "peindre",    en: "to paint",          ex: "Je peins un tableau.",       exEn: "I paint a picture.",     full: ["peins","peins","peint","peignons","peignez","peignent"] }
    ]
  }
};

const PRONOUNS = ["je", "tu", "il / elle", "nous", "vous", "ils / elles"];

if (typeof module !== "undefined") module.exports = { DATA, PRONOUNS };
