/* Vocabulaire A2 — vocabulaire courant, un peu plus varié. */
var VOCAB_A2 = [
  { fr: "le voyage", en: "trip / journey" },
  { fr: "les vacances", en: "vacation / holidays" },
  { fr: "le week-end", en: "weekend" },
  { fr: "la réunion", en: "meeting" },
  { fr: "le rendez-vous", en: "appointment" },
  { fr: "le bureau", en: "office" },
  { fr: "l'entreprise", en: "company" },
  { fr: "le collègue", en: "colleague" },
  { fr: "le patron", en: "boss" },
  { fr: "le salaire", en: "salary" },
  { fr: "le client", en: "customer" },
  { fr: "le service", en: "service" },
  { fr: "le produit", en: "product" },
  { fr: "la facture", en: "invoice / bill" },
  { fr: "le compte", en: "account" },
  { fr: "la banque", en: "bank" },
  { fr: "l'hôpital", en: "hospital" },
  { fr: "le médecin", en: "doctor" },
  { fr: "la maladie", en: "illness" },
  { fr: "la santé", en: "health" },
  { fr: "le médicament", en: "medicine" },
  { fr: "la douleur", en: "pain" },
  { fr: "l'accident", en: "accident" },
  { fr: "le danger", en: "danger" },
  { fr: "la sécurité", en: "safety" },
  { fr: "la police", en: "police" },
  { fr: "la loi", en: "law" },
  { fr: "le droit", en: "right / law" },
  { fr: "le gouvernement", en: "government" },
  { fr: "le pouvoir", en: "power" },
  { fr: "la société", en: "society" },
  { fr: "la culture", en: "culture" },
  { fr: "la religion", en: "religion" },
  { fr: "la fête", en: "party / celebration" },
  { fr: "le mariage", en: "wedding / marriage" },
  { fr: "la naissance", en: "birth" },
  { fr: "la mort", en: "death" },
  { fr: "l'espoir", en: "hope" },
  { fr: "le rêve", en: "dream" },
  { fr: "le souvenir", en: "memory" },
  { fr: "l'expérience", en: "experience" },
  { fr: "le conseil", en: "advice" },
  { fr: "l'erreur", en: "mistake" },
  { fr: "le résultat", en: "result" },
  { fr: "le succès", en: "success" },
  { fr: "l'échec", en: "failure" },
  { fr: "l'effort", en: "effort" },
  { fr: "le courage", en: "courage" },
  { fr: "la peur", en: "fear" },
  { fr: "la surprise", en: "surprise" },
  { fr: "la colère", en: "anger" },
  { fr: "le bonheur", en: "happiness" },
  { fr: "l'amour", en: "love" },
  { fr: "la confiance", en: "trust" },
  { fr: "la vérité", en: "truth" },
  { fr: "le mensonge", en: "lie" },
  { fr: "le secret", en: "secret" },
  { fr: "l'occasion", en: "opportunity" },
  { fr: "le choix", en: "choice" },
  { fr: "la décision", en: "decision" },
  { fr: "le changement", en: "change" },
  { fr: "le début", en: "beginning" },
  { fr: "la fin", en: "end" },
  { fr: "le sujet", en: "subject / topic" },
  { fr: "l'avis", en: "opinion" },
  { fr: "l'importance", en: "importance" },
  { fr: "la qualité", en: "quality" },
  { fr: "la quantité", en: "quantity" },
  { fr: "la taille", en: "size" },
  { fr: "la couleur", en: "color" },
  { fr: "la forme", en: "shape" },
  { fr: "le poids", en: "weight" },
  { fr: "la vitesse", en: "speed" },
  { fr: "la distance", en: "distance" },
  { fr: "la direction", en: "direction" },
  { fr: "le coin", en: "corner" },
  { fr: "le centre", en: "center" },
  { fr: "le niveau", en: "level" },
  { fr: "l'étage", en: "floor (of a building)" },
  { fr: "l'immeuble", en: "building" },
  { fr: "le quartier", en: "neighborhood" },
  { fr: "la campagne", en: "countryside" },
  { fr: "la montagne", en: "mountain" },
  { fr: "la mer", en: "sea" },
  { fr: "la plage", en: "beach" },
  { fr: "la forêt", en: "forest" },
  { fr: "le ciel", en: "sky" },
  { fr: "le soleil", en: "sun" },
  { fr: "la pluie", en: "rain" },
  { fr: "le vent", en: "wind" },
  { fr: "la neige", en: "snow" },
  { fr: "l'orage", en: "storm" },
  { fr: "la saison", en: "season" },
  { fr: "le siècle", en: "century" },
  { fr: "l'histoire", en: "history / story" },
  { fr: "la guerre", en: "war" },
  { fr: "la paix", en: "peace" },
  { fr: "la liberté", en: "freedom" },
  { fr: "l'égalité", en: "equality" },
  { fr: "la justice", en: "justice" },
  { fr: "inquiet", en: "worried" },
  { fr: "déçu", en: "disappointed" },
  { fr: "fier", en: "proud" }
];
