/* Vocabulaire B1 — vocabulaire plus varié, abstrait, nuances. */
var VOCAB_B1 = [
  { fr: "le comportement", en: "behavior" },
  { fr: "l'attitude", en: "attitude" },
  { fr: "la réaction", en: "reaction" },
  { fr: "l'habitude", en: "habit" },
  { fr: "le caractère", en: "character / personality" },
  { fr: "la personnalité", en: "personality" },
  { fr: "la capacité", en: "ability" },
  { fr: "le talent", en: "talent" },
  { fr: "la faiblesse", en: "weakness" },
  { fr: "la force", en: "strength" },
  { fr: "le défi", en: "challenge" },
  { fr: "l'obstacle", en: "obstacle" },
  { fr: "la solution", en: "solution" },
  { fr: "la méthode", en: "method" },
  { fr: "le moyen", en: "means / way" },
  { fr: "l'objectif", en: "goal" },
  { fr: "le but", en: "goal / aim" },
  { fr: "le projet", en: "project" },
  { fr: "l'étape", en: "step / stage" },
  { fr: "le progrès", en: "progress" },
  { fr: "l'amélioration", en: "improvement" },
  { fr: "la conséquence", en: "consequence" },
  { fr: "la cause", en: "cause" },
  { fr: "le facteur", en: "factor" },
  { fr: "le risque", en: "risk" },
  { fr: "l'avantage", en: "advantage" },
  { fr: "l'inconvénient", en: "disadvantage" },
  { fr: "la différence", en: "difference" },
  { fr: "la ressemblance", en: "similarity" },
  { fr: "le point de vue", en: "point of view" },
  { fr: "l'argument", en: "argument" },
  { fr: "la preuve", en: "proof" },
  { fr: "le doute", en: "doubt" },
  { fr: "la certitude", en: "certainty" },
  { fr: "l'inquiétude", en: "worry" },
  { fr: "le soulagement", en: "relief" },
  { fr: "la déception", en: "disappointment" },
  { fr: "la satisfaction", en: "satisfaction" },
  { fr: "la fierté", en: "pride" },
  { fr: "la honte", en: "shame" },
  { fr: "la culpabilité", en: "guilt" },
  { fr: "le regret", en: "regret" },
  { fr: "la jalousie", en: "jealousy" },
  { fr: "la générosité", en: "generosity" },
  { fr: "l'égoïsme", en: "selfishness" },
  { fr: "la patience", en: "patience" },
  { fr: "la sincérité", en: "sincerity" },
  { fr: "l'honnêteté", en: "honesty" },
  { fr: "la trahison", en: "betrayal" },
  { fr: "la loyauté", en: "loyalty" },
  { fr: "le respect", en: "respect" },
  { fr: "la tolérance", en: "tolerance" },
  { fr: "le préjugé", en: "prejudice" },
  { fr: "la discrimination", en: "discrimination" },
  { fr: "l'inégalité", en: "inequality" },
  { fr: "la pauvreté", en: "poverty" },
  { fr: "la richesse", en: "wealth" },
  { fr: "le chômage", en: "unemployment" },
  { fr: "la carrière", en: "career" },
  { fr: "la formation", en: "training" },
  { fr: "la compétence", en: "skill" },
  { fr: "la responsabilité", en: "responsibility" },
  { fr: "l'engagement", en: "commitment" },
  { fr: "l'autonomie", en: "autonomy" },
  { fr: "la dépendance", en: "dependence" },
  { fr: "la relation", en: "relationship" },
  { fr: "le lien", en: "link / bond" },
  { fr: "la rupture", en: "breakup" },
  { fr: "la réconciliation", en: "reconciliation" },
  { fr: "le conflit", en: "conflict" },
  { fr: "le compromis", en: "compromise" },
  { fr: "l'accord", en: "agreement" },
  { fr: "le désaccord", en: "disagreement" },
  { fr: "la négociation", en: "negotiation" },
  { fr: "l'exigence", en: "requirement / demand" },
  { fr: "la contrainte", en: "constraint" },
  { fr: "la liberté d'expression", en: "freedom of speech" },
  { fr: "l'environnement", en: "environment" },
  { fr: "le climat", en: "climate" },
  { fr: "la pollution", en: "pollution" },
  { fr: "les ressources", en: "resources" },
  { fr: "l'énergie", en: "energy" },
  { fr: "le développement", en: "development" },
  { fr: "la croissance", en: "growth" },
  { fr: "la crise", en: "crisis" },
  { fr: "l'économie", en: "economy" },
  { fr: "l'inflation", en: "inflation" },
  { fr: "le marché du travail", en: "job market" },
  { fr: "la mondialisation", en: "globalization" },
  { fr: "la technologie", en: "technology" },
  { fr: "l'innovation", en: "innovation" },
  { fr: "la recherche", en: "research" },
  { fr: "la découverte", en: "discovery" },
  { fr: "le phénomène", en: "phenomenon" },
  { fr: "la théorie", en: "theory" },
  { fr: "le domaine", en: "field / area" },
  { fr: "la perspective", en: "perspective" },
  { fr: "l'enjeu", en: "stake / issue" },
  { fr: "la priorité", en: "priority" },
  { fr: "l'ambition", en: "ambition" },
  { fr: "la réussite", en: "success / achievement" },
  { fr: "l'échéance", en: "deadline" },
  { fr: "l'urgence", en: "urgency" }
];
