/* Vocabulaire A1 — mots du quotidien, les plus fréquents. */
var VOCAB_A1 = [
  { fr: "le temps", en: "time / weather" },
  { fr: "la maison", en: "house" },
  { fr: "l'eau", en: "water" },
  { fr: "le jour", en: "day" },
  { fr: "la nuit", en: "night" },
  { fr: "l'homme", en: "man" },
  { fr: "la femme", en: "woman" },
  { fr: "l'enfant", en: "child" },
  { fr: "l'ami", en: "friend" },
  { fr: "la famille", en: "family" },
  { fr: "la mère", en: "mother" },
  { fr: "le père", en: "father" },
  { fr: "le frère", en: "brother" },
  { fr: "la sœur", en: "sister" },
  { fr: "le fils", en: "son" },
  { fr: "la fille", en: "daughter / girl" },
  { fr: "la ville", en: "city" },
  { fr: "le village", en: "village" },
  { fr: "la rue", en: "street" },
  { fr: "l'école", en: "school" },
  { fr: "le travail", en: "work" },
  { fr: "le magasin", en: "shop" },
  { fr: "le marché", en: "market" },
  { fr: "la voiture", en: "car" },
  { fr: "le train", en: "train" },
  { fr: "le bus", en: "bus" },
  { fr: "l'avion", en: "airplane" },
  { fr: "la route", en: "road" },
  { fr: "le pays", en: "country" },
  { fr: "le monde", en: "world" },
  { fr: "le matin", en: "morning" },
  { fr: "le soir", en: "evening" },
  { fr: "la semaine", en: "week" },
  { fr: "le mois", en: "month" },
  { fr: "l'année", en: "year" },
  { fr: "l'heure", en: "hour / time" },
  { fr: "la minute", en: "minute" },
  { fr: "aujourd'hui", en: "today" },
  { fr: "demain", en: "tomorrow" },
  { fr: "hier", en: "yesterday" },
  { fr: "le repas", en: "meal" },
  { fr: "le pain", en: "bread" },
  { fr: "l'eau minérale", en: "mineral water" },
  { fr: "le lait", en: "milk" },
  { fr: "le café", en: "coffee" },
  { fr: "le thé", en: "tea" },
  { fr: "le fromage", en: "cheese" },
  { fr: "la viande", en: "meat" },
  { fr: "le poisson", en: "fish" },
  { fr: "le fruit", en: "fruit" },
  { fr: "le légume", en: "vegetable" },
  { fr: "la pomme", en: "apple" },
  { fr: "la banane", en: "banana" },
  { fr: "la salade", en: "salad" },
  { fr: "le sucre", en: "sugar" },
  { fr: "le sel", en: "salt" },
  { fr: "la table", en: "table" },
  { fr: "la chaise", en: "chair" },
  { fr: "le lit", en: "bed" },
  { fr: "la porte", en: "door" },
  { fr: "la fenêtre", en: "window" },
  { fr: "la chambre", en: "bedroom" },
  { fr: "la cuisine", en: "kitchen" },
  { fr: "le jardin", en: "garden" },
  { fr: "la clé", en: "key" },
  { fr: "le livre", en: "book" },
  { fr: "le stylo", en: "pen" },
  { fr: "le papier", en: "paper" },
  { fr: "le téléphone", en: "phone" },
  { fr: "l'argent", en: "money" },
  { fr: "le prix", en: "price" },
  { fr: "le nom", en: "name" },
  { fr: "l'adresse", en: "address" },
  { fr: "la question", en: "question" },
  { fr: "la réponse", en: "answer" },
  { fr: "l'idée", en: "idea" },
  { fr: "le problème", en: "problem" },
  { fr: "la chose", en: "thing" },
  { fr: "la personne", en: "person" },
  { fr: "les gens", en: "people" },
  { fr: "le corps", en: "body" },
  { fr: "la tête", en: "head" },
  { fr: "la main", en: "hand" },
  { fr: "le pied", en: "foot" },
  { fr: "les yeux", en: "eyes" },
  { fr: "le cœur", en: "heart" },
  { fr: "grand", en: "big / tall" },
  { fr: "petit", en: "small" },
  { fr: "beau", en: "beautiful" },
  { fr: "joli", en: "pretty" },
  { fr: "bon", en: "good" },
  { fr: "mauvais", en: "bad" },
  { fr: "nouveau", en: "new" },
  { fr: "vieux", en: "old" },
  { fr: "jeune", en: "young" },
  { fr: "content", en: "happy" },
  { fr: "triste", en: "sad" },
  { fr: "fatigué", en: "tired" },
  { fr: "facile", en: "easy" },
  { fr: "difficile", en: "difficult" },
  { fr: "chaud", en: "hot" },
  { fr: "froid", en: "cold" },
  { fr: "rapide", en: "fast" }
];
