/* Vocabulaire B2 — nuancé, registre soutenu, abstrait. */
var VOCAB_B2 = [
  { fr: "l'ambiguïté", en: "ambiguity" },
  { fr: "la nuance", en: "nuance" },
  { fr: "la subtilité", en: "subtlety" },
  { fr: "l'incertitude", en: "uncertainty" },
  { fr: "la complexité", en: "complexity" },
  { fr: "la contradiction", en: "contradiction" },
  { fr: "le paradoxe", en: "paradox" },
  { fr: "l'hypothèse", en: "hypothesis" },
  { fr: "la supposition", en: "assumption" },
  { fr: "la controverse", en: "controversy" },
  { fr: "le débat", en: "debate" },
  { fr: "le consensus", en: "consensus" },
  { fr: "la légitimité", en: "legitimacy" },
  { fr: "l'autorité", en: "authority" },
  { fr: "la crédibilité", en: "credibility" },
  { fr: "la réputation", en: "reputation" },
  { fr: "l'intégrité", en: "integrity" },
  { fr: "l'hypocrisie", en: "hypocrisy" },
  { fr: "la manipulation", en: "manipulation" },
  { fr: "l'influence", en: "influence" },
  { fr: "la pression", en: "pressure" },
  { fr: "la contrainte sociale", en: "social pressure" },
  { fr: "le dilemme", en: "dilemma" },
  { fr: "le renoncement", en: "renunciation / giving up" },
  { fr: "le sacrifice", en: "sacrifice" },
  { fr: "la résilience", en: "resilience" },
  { fr: "la vulnérabilité", en: "vulnerability" },
  { fr: "la fragilité", en: "fragility" },
  { fr: "la ténacité", en: "tenacity" },
  { fr: "la persévérance", en: "perseverance" },
  { fr: "l'obstination", en: "stubbornness" },
  { fr: "la négligence", en: "negligence" },
  { fr: "l'insouciance", en: "carefreeness" },
  { fr: "la lucidité", en: "lucidity" },
  { fr: "la clairvoyance", en: "clear-sightedness" },
  { fr: "l'introspection", en: "introspection" },
  { fr: "la remise en question", en: "self-questioning" },
  { fr: "le recul", en: "hindsight / distance" },
  { fr: "la nostalgie", en: "nostalgia" },
  { fr: "le désenchantement", en: "disillusionment" },
  { fr: "l'indifférence", en: "indifference" },
  { fr: "l'empathie", en: "empathy" },
  { fr: "la compassion", en: "compassion" },
  { fr: "la bienveillance", en: "kindness / benevolence" },
  { fr: "la méfiance", en: "distrust" },
  { fr: "le scepticisme", en: "skepticism" },
  { fr: "la naïveté", en: "naivety" },
  { fr: "la crédulité", en: "gullibility" },
  { fr: "la lassitude", en: "weariness" },
  { fr: "l'épanouissement", en: "fulfillment" },
  { fr: "l'accomplissement", en: "accomplishment" },
  { fr: "la reconnaissance", en: "recognition / gratitude" },
  { fr: "l'injustice", en: "injustice" },
  { fr: "l'inégalité sociale", en: "social inequality" },
  { fr: "la marginalisation", en: "marginalization" },
  { fr: "l'exclusion", en: "exclusion" },
  { fr: "l'intégration", en: "integration" },
  { fr: "la cohésion sociale", en: "social cohesion" },
  { fr: "la solidarité", en: "solidarity" },
  { fr: "le clivage", en: "divide / split" },
  { fr: "la polarisation", en: "polarization" },
  { fr: "l'apaisement", en: "calming / easing" },
  { fr: "l'escalade", en: "escalation" },
  { fr: "la dissuasion", en: "deterrence" },
  { fr: "la répercussion", en: "repercussion" },
  { fr: "l'implication", en: "implication / involvement" },
  { fr: "la portée", en: "scope / significance" },
  { fr: "l'ampleur", en: "extent / magnitude" },
  { fr: "l'envergure", en: "scale / caliber" },
  { fr: "le dénouement", en: "outcome / resolution" },
  { fr: "l'aboutissement", en: "culmination" },
  { fr: "le revirement", en: "turnaround / reversal" },
  { fr: "le tournant", en: "turning point" },
  { fr: "la trajectoire", en: "trajectory / path" },
  { fr: "le parcours", en: "journey / path" },
  { fr: "l'héritage", en: "legacy / inheritance" },
  { fr: "l'empreinte", en: "mark / imprint" },
  { fr: "la transmission", en: "transmission / passing on" },
  { fr: "la postérité", en: "posterity" },
  { fr: "l'anticipation", en: "anticipation" },
  { fr: "la prévision", en: "forecast" },
  { fr: "la spéculation", en: "speculation" },
  { fr: "l'incidence", en: "impact / incidence" },
  { fr: "le préalable", en: "prerequisite" },
  { fr: "la prémisse", en: "premise" },
  { fr: "le fondement", en: "foundation / basis" },
  { fr: "la légitimation", en: "legitimization" },
  { fr: "la remise en cause", en: "questioning / challenging" },
  { fr: "le désaveu", en: "disavowal / repudiation" },
  { fr: "l'adhésion", en: "adherence / support" },
  { fr: "le ralliement", en: "rallying" },
  { fr: "la défiance", en: "defiance / distrust" },
  { fr: "l'insubordination", en: "insubordination" },
  { fr: "la soumission", en: "submission" },
  { fr: "l'émancipation", en: "emancipation" },
  { fr: "l'affranchissement", en: "liberation / freeing" },
  { fr: "la stigmatisation", en: "stigmatization" },
  { fr: "la réhabilitation", en: "rehabilitation" },
  { fr: "l'apaisement des tensions", en: "easing of tensions" },
  { fr: "la précarité", en: "precariousness / instability" },
  { fr: "l'aisance", en: "ease / affluence" },
  { fr: "la disparité", en: "disparity" }
];
